### ISSUE TITLE
Laravel 5 support

### ISSUE THREAD

**Issue by maknz** [maknz/slack#11]
It's my intention to support Laravel 5 ASAP. There is some documentation about package development up, but I've yet to find any kind of upgrade guide. The only problematic thing is config publishing which has changed, I'll need to sort out a backwards-compatible way of doing that.

If there's any L5 experts, feel free to do a PR, but I'll be looking into it anyway.

**Comment by rjmvalk3** [comment]
Any updates on the support?

**Comment by maknz** [comment]
Not yet, I'll try get to it this weekend.

**Comment by maknz** [comment]
Laravel 5 support added in version 1.2.0. Tests well for me, but please open an issue if you spot anything funny.
