### ISSUE TITLE
Slack skips messages if sending "too many"

### ISSUE THREAD

**Issue by pepijnblom** [maknz/slack#18]
Hi, first of all great library, we're really happy to be able to integrate it into our projects. However, we are experiencing a minor problem: if we send messages very quickly Slack seems to stumble and skip some of them.

Right now I'm getting around it by merging the messages into larger ones, but maybe this could be handled in the package itself? (Just an idea)

**Comment by maknz** [comment]
Not really sure if we can handle that on our side. If Slack is rate limiting, perhaps look at queuing up your send jobs with a queue server like Beanstalkd and have the worker only look for new jobs say every 2 seconds, which should make Slack happier and your app faster by not hitting external APIs synchronously. Laravel for example has that kind of queuing functionality baked in, and I've had a lot of success with it.




Glad you're finding the package useful, thanks for the feedback.

**Comment by pepijnblom** [comment]
That's a good idea, we are already using a queue so indeed that would be the best solution for this. Thanks!
