### ISSUE TITLE
Adding as_user and ability to change channel topics

### ISSUE THREAD

**Issue by tjmapes** [maknz/slack#23]
Are these things that would be easily done in the future.  I think they'd be a great addition :)  Any insight or help getting this accomplished would be hugely appreciated.  

I think enabling `as_user` would be great so you don't see `BOT` for every post.  (_if this can't be done I apologize_)

And changing channel topics would be great for Slack community mods whom want to schedule those for whatever particular reason.

**Comment by tjmapes** [comment]
I'm not 100% comfortable with this yet to fork and submit a pull request on my own yet.  Still learning laravel

**Comment by maknz** [comment]
You can use `from()` to change the sender for the particular message.

e.g. `Slack::to('#accounting')->from('Cyril')->send('Hello there!')`

Changing topics in Slack is out of scope of this package. That requires full on use of the Slack API, whereas this package is for sending messages into Slack, which doesn't use the API, but webhooks.

**Comment by tjmapes** [comment]
Thanks for the response @maknz yet using `from()` still shows a `BOT`.  webhook limitation?

**Comment by maknz** [comment]
`BOT` is a label Slack puts beside bots to differentiate them form people. If you say `from('Bart')` it should say Bart and then BOT beside it?

**Comment by tjmapes** [comment]
Ahh yes, what you describe totally works, I was just hoping to avoid showing `BOT`and I think the `as_user` would do that.

**Comment by maknz** [comment]
Right yeah, sorry I misunderstood. I'll ask Slack if that label can be toggled, but I suspect it won't. I'll keep this open til I hear back.

**Comment by tjmapes** [comment]
Thanks @maknz

**Comment by maknz** [comment]
Yep, as suspected, the bot label will always appear for any messages sent via webhooks or the API and cannot be turned off. It's a fair call, so a webhook message wouldn't get confused with a real user. https://twitter.com/SlackHQ/status/606403501703503872

**Comment by tjmapes** [comment]
^ +1
