### ISSUE TITLE
publish in Laravel5.1

### ISSUE THREAD

**Issue by appkr** [maknz/slack#25]
`php artisan vendor:publish --provider=Maknz\Slack\SlackServiceProvider` not works in Laravel5.1. 

`php artisan vendor:publish --provider=Maknz\Slack\SlackServiceProviderLaravel5` works.

**Comment by maknz** [comment]
Does `php artisan config:publish maknz/slack` not work anymore?

**Comment by appkr** [comment]
I haven't tried publish them without --provider option. I know without --force, it will not overwrite previously published assets, but I just want to be cautious.

**Comment by maknz** [comment]
Ah, right, I see. So if you only want to publish config from this one package, so have to address the service provider specifically to only update that config. I'll update the README.

Thanks!
