### ISSUE TITLE
Alternative to autoload

### ISSUE THREAD

**Issue by TheZoker** [maknz/slack#32]
Hi,

is there any option to use this script without autoload?

I only have a usual webspace ...

Thank you
Zoker

**Comment by maknz** [comment]
You can download the project and require in the files manually. It'd be easier to use Composer though.

**Comment by Gummibeer** [comment]
To clear the question: composer will also work on "normal" webspace.
You just have to compile laravel and the autoloader and upload everything via FTP.

**Comment by maknz** [comment]
Thanks for the tip @Gummibeer.
