### ISSUE TITLE
Support for Symfony bundle

### ISSUE THREAD

**Issue by Soullivaneuh** [maknz/slack#37]
I see you have Laravel native support.

Would you accept a PR for Symfony bundle support?

**Comment by maknz** [comment]
I'm not familiar with Symfony bundles so I'm a bit apprehensive about adding support for it.

Maybe you could write your own package which requires `maknz/slack`, but provides whatever interface is required for Symfony bundles?

**Comment by Soullivaneuh** [comment]
> I'm not familiar with Symfony bundles so I'm a bit apprehensive about adding support for it.

This why I'm proposing my help. ;-)

> Maybe you could write your own package which requires maknz/slack, but provides whatever interface is required for Symfony bundles?

Yes I could, but it's easier for users to propose direct implementation on your project.

But yes, I can do that. Maybe you can add a link to your repo when mine will be finished?

**Comment by maknz** [comment]
It'll be my responsibility after it's merged, not something I'm willing to support. Besides, it makes more sense to have further providers added as packages which provide the required functionality for Symfony rather than in the core.

Happy to mention it in the README.

**Comment by Soullivaneuh** [comment]
Ok @maknz I'll start it this week, stay tuned! :+1:

**Comment by Soullivaneuh** [comment]
WIP here: https://github.com/nexylan/NexySlackBundle
