### ISSUE TITLE
Send endpoint with a method

### ISSUE THREAD

**Issue by simplenotezy** [maknz/slack#43]
I need some way to override default endpoint, with a method, like:

    Slack::endpoint($some_url)->to('#channel');

For dynamic slack messages

**Comment by maknz** [comment]
I'd suggest creating multiple clients manually rather than using the facade. There's examples in the documentation about making a client.

**Comment by canfiax** [comment]
But I would like to still keep my config. DRY

**Comment by maknz** [comment]
This has been superseded by the planned multiple teams feature. Thanks for posting this, it was a good catalyst to that discussion (currently over at #44)
