### ISSUE TITLE
README improvements

### ISSUE THREAD

**Issue by maknz** [maknz/slack#49]
I want to make a number of improvements to the README for the next major version:

* [x] Think about splitting the documentation out rathe than dumping it all in the README. Laravel integration could be its own md file.
* [x] Make the examples a bit more real world and interesting. They're a little lazy at the moment.

**Comment by mskenderian** [comment]
the following isnt correct for Laravel 5.2, shouldnt it be
   'Maknz\Slack\SlackServiceProvider::class',

'providers' => [
   'Maknz\Slack\SlackServiceProvider',
],
and then add the facade to your aliases array

'aliases' => [
  ...
  'Slack' => 'Maknz\Slack\Facades\Slack',
],

**Comment by maknz** [comment]
`::class` doesn't work on PHP 5.4 (which is supported on master). The string way worked fine on Laravel 4.x and Laravel 5.0 when originally developed, and there shouldn't have been a breaking change between 5.0 and 5.2. Nobody's ever raised an issue with these, so I suspect they're fine?

**Comment by Gummibeer** [comment]
They are fine and for thoose wanting it the new way it's just a super simple change to do it.
