### ISSUE TITLE
Support for php 5.4

### ISSUE THREAD

**Issue by fboutin-pmc** [maknz/slack#50]
Hi there,
I tried using this component with php 5.4 pulling it from composer like you suggested. The messages could be sent to slack but as soon as the code returned, I would get a crash on `curl_reset` function call.

I finally realized that the version of `guzzle` that composer pulled automatically in regards to the slack `composer.json` definition was version 6, not version 5. So I have to manually specify `guzzle` version 5 into MY `composer.json` file. No brainer.

With all this said and done, that would have been REALLY nice (READ: helpful) to have this info into the README file of your project. For example, a warning statement following the `composer require maknz/slack` snippet.

Regards,

**Comment by maknz** [comment]
Hi there,

That's strange. I've got a feeling Composer for some reason isn't testing your PHP version when evaluating your dependencies. Guzzle 6 has PHP 5.5+ as a constraint in its composer.json, so if you were on 5.4, it should have denied that and fallen back on 5.4.

We're dropping PHP 5.4 support for our next major version (2.0). 5.4 has reached end of life support, and so will 5.5 in just a month. http://php.net/supported-versions.php

**Comment by fboutin-pmc** [comment]
TBH, I'm new with Composer and PHP. I had this feeling that Composer probably automatically evaluates my current version of PHP.

I'm currently configured with a local version of PHP that is higher than the one used remotely. So I'm pretty sure I'm at fault here with my setup.

I'm taking notes. We definitely need to move to PHP 5.5 soon.

Thanks for you input @maknz.
No need to add anything into the README then.

Cheers,
