### ISSUE TITLE
can't generate config file

### ISSUE THREAD

**Issue by westwick** [maknz/slack#53]
I have a brand new installation of Laravel 5.2 and after adding the package with `composer require maknz/slack` (Using version ^1.7 for maknz/slack) and then trying to run `php artisan vendor:publish --provider="Maknz/Slack/SlackServiceProviderLaravel5"` I get the following output:

Nothing to publish for tag [].

Did I miss something?

**Comment by drewbix** [comment]
Running just `php artisan vendor:publish` created the config btw, just thought you might want to know for the purpose of the docs. The readme is also a bit confusing about how to add the laravel provider/facade (its using 5.0 style instead of 5.2). Just an FYI! Appreciate your work on this package.

**Comment by maknz** [comment]
Looks like your slashes are forward and not back? It should be `Maknz\Slack\SlackServiceProviderLaravel5` as per the README.

**Comment by drewbix** [comment]
Er, I tried both ways and just pasted my second attempt:

$ php artisan vendor:publish --provider="Maknz\Slack\SlackServiceProviderLaravel5"
Nothing to publish for tag [].
$ php artisan vendor:publish --provider="Maknz/Slack/SlackServiceProviderLaravel5"
Nothing to publish for tag [].

**Comment by maknz** [comment]
Could you try `php artisan config:clear && php artisan vendor:publish --provider="Maknz\Slack\SlackServiceProviderLaravel5"`?

**Comment by drewbix** [comment]
Sorry for the delay, after installing several other packages which all use simply `php artisan vendor:publish` (with no provider flag), I believe it's just a small syntax change in Laravel -- although I haven't investigated the release notes or code.

**Comment by maknz** [comment]
@westwick cool. Could you link me to the packages you're using that have just the `vendor:publish` instructions? I'll make sure our service providers work like theirs, and look to changes. If it's indeed the correct way of doing things, more than happy to change it.

Re: your PR, happy to merge your `::class` changes now, or we can wait until I've researched the config publishing stuff.

Thanks!

**Comment by maknz** [comment]
@westwick quick update for you - encountered the same issue with config publishing, and seems the way you proposed is the way to go. I'm also moving the Laravel integration into a different package - check out https://github.com/maknz/slack-laravel.

**Comment by westwick** [comment]
👍
