### ISSUE TITLE
Having trouble installing

### ISSUE THREAD

**Issue by samr28** [maknz/slack#63]
I ran composer require maknz/slack and all of the src was added to the vendor folder.  I have created a file called slackTest.php which includes the basic usage code (with my hooks url)  I am getting the error: Fatal error: Class 'Maknz\Slack\Client' not found in /home/ubuntu/workspace/vendor/maknz/slack/slackTest.php on line 3.

**Comment by funkytaco** [comment]
How'd you fix this?

**Comment by samr28** [comment]
Do you have "require '/home/ubuntu/workspace/vendor/autoload.php';" on your page?

**Comment by tridentechnologies** [comment]
Where can I get autoload.php file.? I am using centos 7
