### ISSUE TITLE
Markdown options

### ISSUE THREAD

**Issue by andersonamuller** [maknz/slack#9]
Hi,

First, thanks for the work in this package, really nice. 
Have you thought about adding the markdown formatting options (`mrkdwn`, `mrkdwn_in`) to the message and attachments?
https://api.slack.com/docs/formatting

I could do a PR, but just in a couple of weeks.

**Comment by maknz** [comment]
Slack really like to hide these options away don't they! Looks cool, I'll look at adding this in the weekend. Glad you like the package.

**Comment by maknz** [comment]
Added in v1.1.0 :+1:

**Comment by andersonamuller** [comment]
:+1:  nice, thanks.
